/* AUTO-GENERATED by scripts/generate-questions.mjs — ne pas modifier à la main sauf intention */
import type { InterviewQuestion } from './types';

export const CATEGORIES = [
  {
    "id": "firm-culture",
    "label": "Firme et culture",
    "count": 10
  },
  {
    "id": "strategy",
    "label": "Pilier Stratégie",
    "count": 8
  },
  {
    "id": "innovation",
    "label": "Pilier Innovation",
    "count": 8
  },
  {
    "id": "ecosystem",
    "label": "Pilier Écosystème",
    "count": 6
  },
  {
    "id": "intelligence",
    "label": "Pilier Intelligence",
    "count": 6
  },
  {
    "id": "case-style",
    "label": "Études de cas et mandats",
    "count": 12
  },
  {
    "id": "sectors",
    "label": "Connaissance sectorielle",
    "count": 10
  },
  {
    "id": "behavioral",
    "label": "Comportemental (STAR)",
    "count": 10
  },
  {
    "id": "relocation",
    "label": "Relocalisation et présence sur site",
    "count": 12
  },
  {
    "id": "small-team",
    "label": "Petite équipe (<50)",
    "count": 8
  },
  {
    "id": "compensation",
    "label": "Rémunération",
    "count": 5
  },
  {
    "id": "curveball",
    "label": "Questions difficiles / pièges",
    "count": 5
  }
] as const;

export const questions: InterviewQuestion[] = [
  {
    "id": "q001",
    "categoryId": "firm-culture",
    "question": "Que savez-vous de Volume10 / VolumE Dix, et pourquoi notre signature « Donner de l'espace aux idées » vous parle-t-elle ?",
    "answerBullets": [
      "Relier la signature à la méthode boutique : provocation, acteurs inhabituels, place pour des solutions non évidentes",
      "Mentionner le repositionnement : cabinet-conseil exécutif, décisions sous pression",
      "Lignée IdéesFx — créatif/stratégique, pas le modèle Big Four générique"
    ],
    "fullScript": "Ouverture : « Que savez-vous de Volume10 / VolumE Dix, et pourquoi notre signature « Donner de l'espace aux idées » vous parle-t-elle  ? » — Voici comment je le cadre pour Volume10.\n\n1. Relier la signature à la méthode boutique : provocation, acteurs inhabituels, place pour des solutions non évidentes\n2. Mentionner le repositionnement : cabinet-conseil exécutif, décisions sous pression\n3. Lignée IdéesFx — créatif/stratégique, pas le modèle Big Four générique\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Firme et culture"
    ],
    "bilingualRequired": true,
    "context": "Question d'ouverture culture firme — panel associé",
    "interviewerVariants": [
      "Que signifie « donner de l'espace aux idées » pour vous, concrètement ?",
      "Pourquoi cette signature plutôt qu'un pitch classique de cabinet ?"
    ],
    "difficulty": "standard"
  },
  {
    "id": "q002",
    "categoryId": "firm-culture",
    "question": "En quoi une boutique comme Volume10 diffère-t-elle de McKinsey ou Accenture, et où vous situez-vous ?",
    "answerBullets": [
      "Équipes plus petites, accès aux associés, mandats sur mesure",
      "Vous apportez de la profondeur sans bureaucratie; citez l'autonomie sur des mandats passés",
      "Respecter leur équipe riche en anciens — vous ajoutez une perspective internationale"
    ],
    "fullScript": "Ouverture : « En quoi une boutique comme Volume10 diffère-t-elle de McKinsey ou Accenture, et où vous situez-vous  ? » — Voici comment je le cadre pour Volume10.\n\n1. Équipes plus petites, accès aux associés, mandats sur mesure\n2. Vous apportez de la profondeur sans bureaucratie; citez l'autonomie sur des mandats passés\n3. Respecter leur équipe riche en anciens — vous ajoutez une perspective internationale\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Firme et culture"
    ]
  },
  {
    "id": "q003",
    "categoryId": "firm-culture",
    "question": "Volume10 travaille étroitement avec IdéesFx — que signifie cet écosystème pour un consultant ?",
    "answerBullets": [
      "Mélange créatif + stratégique; pollinisation croisée des méthodes",
      "À l'aise avec l'ambiguïté et la proximité du design thinking",
      "Le client voit une seule équipe intégrée"
    ],
    "fullScript": "Ouverture : « Volume10 travaille étroitement avec IdéesFx — que signifie cet écosystème pour un consultant  ? » — Voici comment je le cadre pour Volume10.\n\n1. Mélange créatif + stratégique; pollinisation croisée des méthodes\n2. À l'aise avec l'ambiguïté et la proximité du design thinking\n3. Le client voit une seule équipe intégrée\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Firme et culture"
    ],
    "bilingualRequired": true
  },
  {
    "id": "q004",
    "categoryId": "firm-culture",
    "question": "Pourquoi Montréal et le marché bilingue du Québec comptent pour ce rôle.",
    "answerBullets": [
      "Gestion des parties prenantes en français et en anglais; normes du secteur public",
      "Vous investirez dans un plan de montée en français professionnel",
      "Exemples de livrables bilingues"
    ],
    "fullScript": "Ouverture : « Pourquoi Montréal et le marché bilingue du Québec comptent pour ce rôle. ? » — Voici comment je le cadre pour Volume10.\n\n1. Gestion des parties prenantes en français et en anglais; normes du secteur public\n2. Vous investirez dans un plan de montée en français professionnel\n3. Exemples de livrables bilingues\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Firme et culture"
    ],
    "bilingualRequired": true
  },
  {
    "id": "q005",
    "categoryId": "firm-culture",
    "question": "Quelle est notre mission (« relever les défis autrement ») avec vos propres mots ?",
    "answerBullets": [
      "Solutions intelligentes et durables; analyse rigoureuse + étude d'impact",
      "Pas une usine à slides — outiller le client pour l'action et l'alignement",
      "Offrir un manifeste de 30 secondes en écho"
    ],
    "fullScript": "Ouverture : « Quelle est notre mission (« relever les défis autrement ») avec vos propres mots  ? » — Voici comment je le cadre pour Volume10.\n\n1. Solutions intelligentes et durables; analyse rigoureuse + étude d'impact\n2. Pas une usine à slides — outiller le client pour l'action et l'alignement\n3. Offrir un manifeste de 30 secondes en écho\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Firme et culture"
    ]
  },
  {
    "id": "q006",
    "categoryId": "firm-culture",
    "question": "Comment gérez-vous la tension entre provocation et politique client ?",
    "answerBullets": [
      "Volume10 provoque des acteurs inhabituels avec respect",
      "STAR : atelier où vous avez fait émerger une vérité inconfortable avec adhésion",
      "Conclure sur l'alignement des résultats partagés"
    ],
    "fullScript": "Ouverture : « Comment gérez-vous la tension entre provocation et politique client  ? » — Voici comment je le cadre pour Volume10.\n\n1. Volume10 provoque des acteurs inhabituels avec respect\n2. STAR : atelier où vous avez fait émerger une vérité inconfortable avec adhésion\n3. Conclure sur l'alignement des résultats partagés\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Firme et culture"
    ]
  },
  {
    "id": "q007",
    "categoryId": "firm-culture",
    "question": "Qu'avez-vous retenu de notre portefeuille d'études de cas qui vous enthousiasme le plus ?",
    "answerBullets": [
      "Choisir 2 : innovation CUSM, planification Transplant Québec, revitalisation Griffintown",
      "Lier à votre expérience sectorielle",
      "Montrer que vous avez lu les résultats, pas seulement les titres"
    ],
    "fullScript": "Ouverture : « Qu'avez-vous retenu de notre portefeuille d'études de cas qui vous enthousiasme le plus  ? » — Voici comment je le cadre pour Volume10.\n\n1. Choisir 2 : innovation CUSM, planification Transplant Québec, revitalisation Griffintown\n2. Lier à votre expérience sectorielle\n3. Montrer que vous avez lu les résultats, pas seulement les titres\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Firme et culture"
    ],
    "relatedCaseStudy": "Stratégie d'innovation pour le CUSM"
  },
  {
    "id": "q008",
    "categoryId": "firm-culture",
    "question": "Comment représenteriez-vous Volume10 lors d'un premier atelier client ?",
    "answerBullets": [
      "Écouter d'abord — « donner de l'espace »",
      "Ordre du jour structuré, sensibilité bilingue",
      "Quitter avec prochaines étapes claires et carte des sponsors"
    ],
    "fullScript": "Ouverture : « Comment représenteriez-vous Volume10 lors d'un premier atelier client  ? » — Voici comment je le cadre pour Volume10.\n\n1. Écouter d'abord — « donner de l'espace »\n2. Ordre du jour structuré, sensibilité bilingue\n3. Quitter avec prochaines étapes claires et carte des sponsors\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Firme et culture"
    ]
  },
  {
    "id": "q009",
    "categoryId": "firm-culture",
    "question": "Où voyez-vous Volume10 dans 3 ans compte tenu du repositionnement VolumE Dix ?",
    "answerBullets": [
      "Croissance en conseil exécutif; ligne de produits Intelligence",
      "Guerre des talents à Montréal — vous renforcez l'effectif",
      "Vous voulez grandir avec la firme, pas l'utiliser comme tremplin"
    ],
    "fullScript": "Ouverture : « Où voyez-vous Volume10 dans 3 ans compte tenu du repositionnement VolumE Dix  ? » — Voici comment je le cadre pour Volume10.\n\n1. Croissance en conseil exécutif; ligne de produits Intelligence\n2. Guerre des talents à Montréal — vous renforcez l'effectif\n3. Vous voulez grandir avec la firme, pas l'utiliser comme tremplin\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Firme et culture"
    ],
    "context": "Aligné offre mai 2026 — 4 consultants exécutifs",
    "interviewerVariants": [
      "Pourquoi postuler maintenant alors que vous êtes encore en Grèce ?",
      "Qu'attendez-vous des responsabilités rapides annoncées ?"
    ],
    "difficulty": "standard"
  },
  {
    "id": "q010",
    "categoryId": "firm-culture",
    "question": "Pourquoi le conseil exécutif chez Volume Dix maintenant — et pourquoi l'un de nos 4 postes consultants ?",
    "answerBullets": [
      "Aligner sur l'offre : travail direct dirigeants, responsabilités rapides, présentiel Vieux-Montréal",
      "Inflexion : fin mandat Deloitte, mobilité Grèce→Canada, pas pivot opportuniste",
      "Profil atypique ECT/ENCG/compliance comme atout (l'annonce l'encourage)"
    ],
    "fullScript": "Ouverture : « Pourquoi le conseil exécutif chez Volume Dix maintenant — et pourquoi l'un de nos 4 postes consultants  ? » — Voici comment je le cadre pour Volume10.\n\n1. Aligner sur l'offre : travail direct dirigeants, responsabilités rapides, présentiel Vieux-Montréal\n2. Inflexion : fin mandat Deloitte, mobilité Grèce→Canada, pas pivot opportuniste\n3. Profil atypique ECT/ENCG/compliance comme atout (l'annonce l'encourage)\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Firme et culture"
    ],
    "context": "Croissance du cabinet — associé fondateur",
    "interviewerVariants": [
      "Comment contribueriez-vous à la croissance dès la première année ?",
      "Que laisseriez-vous au cabinet si vous partez dans 3 ans ?"
    ],
    "difficulty": "followUp"
  },
  {
    "id": "q011",
    "categoryId": "strategy",
    "question": "Comment mèneriez-vous une retraite de planification stratégique pour une institution publique ?",
    "answerBullets": [
      "Entrevues préparatoires, arbre de problèmes, scénarios",
      "Animation avec dirigeants et terrain",
      "Livrable : choix, indicateurs, rythme de gouvernance"
    ],
    "fullScript": "Ouverture : « Comment mèneriez-vous une retraite de planification stratégique pour une institution publique  ? » — Voici comment je le cadre pour Volume10.\n\n1. Entrevues préparatoires, arbre de problèmes, scénarios\n2. Animation avec dirigeants et terrain\n3. Livrable : choix, indicateurs, rythme de gouvernance\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Pilier Stratégie"
    ],
    "context": "Pilier Stratégie — manager de mandat",
    "interviewerVariants": [
      "Comment aborderiez-vous un plan stratégique pour un client public ?"
    ],
    "difficulty": "standard"
  },
  {
    "id": "q012",
    "categoryId": "strategy",
    "question": "Comment bâtissez-vous un dossier d'affaires qui résiste à l'examen du conseil d'administration ?",
    "answerBullets": [
      "Coûts, bénéfices, risques, analyse de sensibilité",
      "Langage de reddition de comptes du secteur public québécois",
      "Pilote avant mise à l'échelle"
    ],
    "fullScript": "Ouverture : « Comment bâtissez-vous un dossier d'affaires qui résiste à l'examen du conseil d'administration  ? » — Voici comment je le cadre pour Volume10.\n\n1. Coûts, bénéfices, risques, analyse de sensibilité\n2. Langage de reddition de comptes du secteur public québécois\n3. Pilote avant mise à l'échelle\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Pilier Stratégie"
    ]
  },
  {
    "id": "q013",
    "categoryId": "strategy",
    "question": "Décrivez votre approche de diagnostic interne avant de recommander une stratégie.",
    "answerBullets": [
      "Carte des parties prenantes, revue des données, touches ethnographiques",
      "Distinguer symptômes et causes profondes",
      "Volume10 : analyse rigoureuse avant solution sur mesure"
    ],
    "fullScript": "Ouverture : « Décrivez votre approche de diagnostic interne avant de recommander une stratégie. ? » — Voici comment je le cadre pour Volume10.\n\n1. Carte des parties prenantes, revue des données, touches ethnographiques\n2. Distinguer symptômes et causes profondes\n3. Volume10 : analyse rigoureuse avant solution sur mesure\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Pilier Stratégie"
    ]
  },
  {
    "id": "q014",
    "categoryId": "strategy",
    "question": "Comment coachez-vous un PDG qui n'est pas d'accord avec votre recommandation ?",
    "answerBullets": [
      "Identifier la décision qu'il doit assumer",
      "Preuves + petites expérimentations",
      "Préserver la relation — la boutique vit de la confiance"
    ],
    "fullScript": "Ouverture : « Comment coachez-vous un PDG qui n'est pas d'accord avec votre recommandation  ? » — Voici comment je le cadre pour Volume10.\n\n1. Identifier la décision qu'il doit assumer\n2. Preuves + petites expérimentations\n3. Préserver la relation — la boutique vit de la confiance\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Pilier Stratégie"
    ]
  },
  {
    "id": "q015",
    "categoryId": "strategy",
    "question": "Quels cadres utilisez-vous — et quand les abandonnez-vous ?",
    "answerBullets": [
      "SWOT, OKR, chaîne de valeur — selon le contexte",
      "Les cadres servent la conversation, ne la remplacent pas",
      "Exemple où la simplicité a gagné"
    ],
    "fullScript": "Ouverture : « Quels cadres utilisez-vous — et quand les abandonnez-vous  ? » — Voici comment je le cadre pour Volume10.\n\n1. SWOT, OKR, chaîne de valeur — selon le contexte\n2. Les cadres servent la conversation, ne la remplacent pas\n3. Exemple où la simplicité a gagné\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Pilier Stratégie"
    ]
  },
  {
    "id": "q016",
    "categoryId": "strategy",
    "question": "Comment alignez-vous modèles financiers et récit stratégique ?",
    "answerBullets": [
      "Un seul fil narratif des chiffres à la mission",
      "Tester les hypothèses avec la finance client",
      "Logique d'investissement en innovation type CUSM"
    ],
    "fullScript": "Ouverture : « Comment alignez-vous modèles financiers et récit stratégique  ? » — Voici comment je le cadre pour Volume10.\n\n1. Un seul fil narratif des chiffres à la mission\n2. Tester les hypothèses avec la finance client\n3. Logique d'investissement en innovation type CUSM\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Pilier Stratégie"
    ]
  },
  {
    "id": "q017",
    "categoryId": "strategy",
    "question": "Expérience de plans stratégiques pour la santé ou l'éducation ?",
    "answerBullets": [
      "Réglementation sectorielle, ministères",
      "Résultats vs livrables",
      "Référencer Transplant Québec / modèles collégiaux du site"
    ],
    "fullScript": "Ouverture : « Expérience de plans stratégiques pour la santé ou l'éducation  ? » — Voici comment je le cadre pour Volume10.\n\n1. Réglementation sectorielle, ministères\n2. Résultats vs livrables\n3. Référencer Transplant Québec / modèles collégiaux du site\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Pilier Stratégie"
    ]
  },
  {
    "id": "q018",
    "categoryId": "strategy",
    "question": "Comment mesurez-vous l'impact après l'approbation de la stratégie ?",
    "answerBullets": [
      "Indicateurs avancés/retardés, jalons à 90 jours",
      "Étude d'impact — promesse Volume10",
      "Corriger le cap ouvertement"
    ],
    "fullScript": "Ouverture : « Comment mesurez-vous l'impact après l'approbation de la stratégie  ? » — Voici comment je le cadre pour Volume10.\n\n1. Indicateurs avancés/retardés, jalons à 90 jours\n2. Étude d'impact — promesse Volume10\n3. Corriger le cap ouvertement\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Pilier Stratégie"
    ]
  },
  {
    "id": "q019",
    "categoryId": "innovation",
    "question": "Comment définissez-vous l'innovation dans un réseau hospitalier vs une startup technologique ?",
    "answerBullets": [
      "CUSM : gouvernance, adoption clinique, risque",
      "Startup : vitesse; hôpital : sécurité et équité",
      "Vous faites le pont entre les deux vocabulaires"
    ],
    "fullScript": "Ouverture : « Comment définissez-vous l'innovation dans un réseau hospitalier vs une startup technologique  ? » — Voici comment je le cadre pour Volume10.\n\n1. CUSM : gouvernance, adoption clinique, risque\n2. Startup : vitesse; hôpital : sécurité et équité\n3. Vous faites le pont entre les deux vocabulaires\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Pilier Innovation"
    ],
    "context": "Pilier Innovation",
    "interviewerVariants": [
      "Donnez un exemple d'innovation processus, pas produit."
    ],
    "difficulty": "standard"
  },
  {
    "id": "q020",
    "categoryId": "innovation",
    "question": "Décrivez la construction d'une feuille de route d'innovation avec les équipes technologie et opérations.",
    "answerBullets": [
      "Horizon 1-2-3 ou équivalent",
      "Dépendances, pilotes, critères de passage à l'échelle",
      "Gouvernance des données explicite"
    ],
    "fullScript": "Ouverture : « Décrivez la construction d'une feuille de route d'innovation avec les équipes technologie et opérations. ? » — Voici comment je le cadre pour Volume10.\n\n1. Horizon 1-2-3 ou équivalent\n2. Dépendances, pilotes, critères de passage à l'échelle\n3. Gouvernance des données explicite\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Pilier Innovation"
    ]
  },
  {
    "id": "q021",
    "categoryId": "innovation",
    "question": "Comment gérez-vous le théâtre de l'innovation — ateliers sans suite ?",
    "answerBullets": [
      "Lier aux indicateurs et aux sponsors",
      "Mettre fin aux projets favoris avec tact",
      "Victoires rapides en 60 jours"
    ],
    "fullScript": "Ouverture : « Comment gérez-vous le théâtre de l'innovation — ateliers sans suite  ? » — Voici comment je le cadre pour Volume10.\n\n1. Lier aux indicateurs et aux sponsors\n2. Mettre fin aux projets favoris avec tact\n3. Victoires rapides en 60 jours\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Pilier Innovation"
    ]
  },
  {
    "id": "q022",
    "categoryId": "innovation",
    "question": "Expérience en santé numérique ou soins connectés ?",
    "answerBullets": [
      "Parcours patient, interopérabilité, gestion du changement",
      "Langage des études de cas en soins connectés",
      "Sensibilisation vie privée / RAMQ"
    ],
    "fullScript": "Ouverture : « Expérience en santé numérique ou soins connectés  ? » — Voici comment je le cadre pour Volume10.\n\n1. Parcours patient, interopérabilité, gestion du changement\n2. Langage des études de cas en soins connectés\n3. Sensibilisation vie privée / RAMQ\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Pilier Innovation"
    ]
  },
  {
    "id": "q023",
    "categoryId": "innovation",
    "question": "Comment instaurer une gouvernance de l'innovation sans ralentir les équipes ?",
    "answerBullets": [
      "Stage-gate léger",
      "Droits de décision clairs",
      "Cadence de revue de portefeuille"
    ],
    "fullScript": "Ouverture : « Comment instaurer une gouvernance de l'innovation sans ralentir les équipes  ? » — Voici comment je le cadre pour Volume10.\n\n1. Stage-gate léger\n2. Droits de décision clairs\n3. Cadence de revue de portefeuille\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Pilier Innovation"
    ]
  },
  {
    "id": "q024",
    "categoryId": "innovation",
    "question": "Parlez-nous d'une transformation où stratégie numérique et changement culturel se sont rencontrés.",
    "answerBullets": [
      "Format STAR",
      "Résistances rencontrées",
      "Mesures d'adoption"
    ],
    "fullScript": "Ouverture : « Parlez-nous d'une transformation où stratégie numérique et changement culturel se sont rencontrés. ? » — Voici comment je le cadre pour Volume10.\n\n1. Format STAR\n2. Résistances rencontrées\n3. Mesures d'adoption\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Pilier Innovation"
    ]
  },
  {
    "id": "q025",
    "categoryId": "innovation",
    "question": "Comment clarifieriez-vous les concepts d'innovation pour des dirigeants non experts ?",
    "answerBullets": [
      "Langage clair, métaphores, visuels",
      "Lien avec l'étude Volume10 : diffusion de concepts",
      "Éviter le jargon"
    ],
    "fullScript": "Ouverture : « Comment clarifieriez-vous les concepts d'innovation pour des dirigeants non experts  ? » — Voici comment je le cadre pour Volume10.\n\n1. Langage clair, métaphores, visuels\n2. Lien avec l'étude Volume10 : diffusion de concepts\n3. Éviter le jargon\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Pilier Innovation"
    ]
  },
  {
    "id": "q026",
    "categoryId": "innovation",
    "question": "Quel rôle jouent les données dans votre travail d'innovation ?",
    "answerBullets": [
      "Preuves pour la priorisation",
      "Éthique et biais",
      "Synergie avec le pilier Intelligence"
    ],
    "fullScript": "Ouverture : « Quel rôle jouent les données dans votre travail d'innovation  ? » — Voici comment je le cadre pour Volume10.\n\n1. Preuves pour la priorisation\n2. Éthique et biais\n3. Synergie avec le pilier Intelligence\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Pilier Innovation"
    ]
  },
  {
    "id": "q027",
    "categoryId": "ecosystem",
    "question": "Comment cartographiez-vous un écosystème de parties prenantes pour un projet d'infrastructure ?",
    "answerBullets": [
      "Acteurs, incitatifs, pouvoir, flux",
      "Angle encombrement minimal / chantier innovant",
      "Plan d'engagement par cluster"
    ],
    "fullScript": "Ouverture : « Comment cartographiez-vous un écosystème de parties prenantes pour un projet d'infrastructure  ? » — Voici comment je le cadre pour Volume10.\n\n1. Acteurs, incitatifs, pouvoir, flux\n2. Angle encombrement minimal / chantier innovant\n3. Plan d'engagement par cluster\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Pilier Écosystème"
    ],
    "context": "Pilier Écosystème — client institutionnel",
    "interviewerVariants": [
      "Comment mobiliser des parties prenantes externes ?"
    ],
    "difficulty": "standard"
  },
  {
    "id": "q028",
    "categoryId": "ecosystem",
    "question": "Décrivez la mobilisation de ménages vulnérables dans un programme d'efficacité énergétique.",
    "answerBullets": [
      "Thèmes des études de cas Volume10",
      "Confiance, partenaires communautaires",
      "Mesurer la participation, pas seulement les installations"
    ],
    "fullScript": "Ouverture : « Décrivez la mobilisation de ménages vulnérables dans un programme d'efficacité énergétique. ? » — Voici comment je le cadre pour Volume10.\n\n1. Thèmes des études de cas Volume10\n2. Confiance, partenaires communautaires\n3. Mesurer la participation, pas seulement les installations\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Pilier Écosystème"
    ]
  },
  {
    "id": "q029",
    "categoryId": "ecosystem",
    "question": "Comment soutenez-vous les clients dans des présentations de financement sans surpromettre ?",
    "answerBullets": [
      "Récit + preuves + demande",
      "Divulgation des risques",
      "Coaching de la prestation"
    ],
    "fullScript": "Ouverture : « Comment soutenez-vous les clients dans des présentations de financement sans surpromettre  ? » — Voici comment je le cadre pour Volume10.\n\n1. Récit + preuves + demande\n2. Divulgation des risques\n3. Coaching de la prestation\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Pilier Écosystème"
    ]
  },
  {
    "id": "q030",
    "categoryId": "ecosystem",
    "question": "Exemple de pensée systémique qui a changé la stratégie d'un client.",
    "answerBullets": [
      "Boucles de rétroaction identifiées",
      "Point d'intervention choisi",
      "Résultat"
    ],
    "fullScript": "Ouverture : « Exemple de pensée systémique qui a changé la stratégie d'un client. ? » — Voici comment je le cadre pour Volume10.\n\n1. Boucles de rétroaction identifiées\n2. Point d'intervention choisi\n3. Résultat\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Pilier Écosystème"
    ]
  },
  {
    "id": "q031",
    "categoryId": "ecosystem",
    "question": "Comment gérez-vous les conflits entre partenaires d'écosystème ?",
    "answerBullets": [
      "Facilitation neutre",
      "Indicateurs partagés",
      "Voies d'escalade"
    ],
    "fullScript": "Ouverture : « Comment gérez-vous les conflits entre partenaires d'écosystème  ? » — Voici comment je le cadre pour Volume10.\n\n1. Facilitation neutre\n2. Indicateurs partagés\n3. Voies d'escalade\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Pilier Écosystème"
    ],
    "relatedCaseStudy": "Stratégie d'innovation pour le CUSM"
  },
  {
    "id": "q032",
    "categoryId": "ecosystem",
    "question": "Expérience d'alignement des parties prenantes en partenariat public-privé ?",
    "answerBullets": [
      "Rôles, gouvernance, communications",
      "Contexte québécois si applicable",
      "Confiance à long terme"
    ],
    "fullScript": "Ouverture : « Expérience d'alignement des parties prenantes en partenariat public-privé  ? » — Voici comment je le cadre pour Volume10.\n\n1. Rôles, gouvernance, communications\n2. Contexte québécois si applicable\n3. Confiance à long terme\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Pilier Écosystème"
    ],
    "relatedCaseStudy": "Encombrement minimal — Gestion innovante des chantiers"
  },
  {
    "id": "q033",
    "categoryId": "intelligence",
    "question": "En quoi Volume10 Intelligence diffère-t-il du conseil stratégique classique ?",
    "answerBullets": [
      "Études sectorielles, prospective, leadership de pensée ciblé",
      "Génération de prospects + crédibilité",
      "Vous savez rédiger des synthèses exécutives"
    ],
    "fullScript": "Ouverture : « En quoi Volume10 Intelligence diffère-t-il du conseil stratégique classique  ? » — Voici comment je le cadre pour Volume10.\n\n1. Études sectorielles, prospective, leadership de pensée ciblé\n2. Génération de prospects + crédibilité\n3. Vous savez rédiger des synthèses exécutives\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Pilier Intelligence"
    ],
    "relatedCaseStudy": "Initiative de revitalisation de Griffintown",
    "context": "Intelligence / quantitatif",
    "interviewerVariants": [
      "Comment combinez-vous données et jugement ?"
    ],
    "difficulty": "followUp"
  },
  {
    "id": "q034",
    "categoryId": "intelligence",
    "question": "Décrivez une analyse sectorielle qui a influencé une stratégie.",
    "answerBullets": [
      "Méthode : sources, entrevues, benchmarks",
      "Insight qui a surpris le client",
      "Recommandation"
    ],
    "fullScript": "Ouverture : « Décrivez une analyse sectorielle qui a influencé une stratégie. ? » — Voici comment je le cadre pour Volume10.\n\n1. Méthode : sources, entrevues, benchmarks\n2. Insight qui a surpris le client\n3. Recommandation\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Pilier Intelligence"
    ],
    "relatedCaseStudy": "Plan stratégique Transplant Québec 2023–2027"
  },
  {
    "id": "q035",
    "categoryId": "intelligence",
    "question": "Comment faites-vous de la prospective sans paraître spéculatif ?",
    "answerBullets": [
      "Scénarios avec signaux faibles",
      "Implications, pas prédictions",
      "Déclencheurs de décision"
    ],
    "fullScript": "Ouverture : « Comment faites-vous de la prospective sans paraître spéculatif  ? » — Voici comment je le cadre pour Volume10.\n\n1. Scénarios avec signaux faibles\n2. Implications, pas prédictions\n3. Déclencheurs de décision\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Pilier Intelligence"
    ],
    "relatedCaseStudy": "Conception d'une stratégie d'engagement pour les ménages vulnérables"
  },
  {
    "id": "q036",
    "categoryId": "intelligence",
    "question": "Comment amélioreriez-vous la capture de prospects pour les téléchargements PDF Intelligence ?",
    "answerBullets": [
      "Friction du formulaire vs valeur",
      "Nurturing de suivi",
      "Actifs bilingues"
    ],
    "fullScript": "Ouverture : « Comment amélioreriez-vous la capture de prospects pour les téléchargements PDF Intelligence  ? » — Voici comment je le cadre pour Volume10.\n\n1. Friction du formulaire vs valeur\n2. Nurturing de suivi\n3. Actifs bilingues\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Pilier Intelligence"
    ],
    "relatedCaseStudy": "Feuille de route d'innovation du CHU de Québec"
  },
  {
    "id": "q037",
    "categoryId": "intelligence",
    "question": "Quelles tendances d'innovation en santé au Québec devrions-nous surveiller ?",
    "answerBullets": [
      "Vieillissement, main-d'œuvre, portail numérique, gouvernance de l'IA",
      "Écosystème Santé Québec",
      "Lien avec le travail CUSM"
    ],
    "fullScript": "Ouverture : « Quelles tendances d'innovation en santé au Québec devrions-nous surveiller  ? » — Voici comment je le cadre pour Volume10.\n\n1. Vieillissement, main-d'œuvre, portail numérique, gouvernance de l'IA\n2. Écosystème Santé Québec\n3. Lien avec le travail CUSM\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Pilier Intelligence"
    ],
    "relatedCaseStudy": "La Table Ronde — Gastronomie québécoise"
  },
  {
    "id": "q038",
    "categoryId": "intelligence",
    "question": "Comment synthétisez-vous les meilleures pratiques mondiales pour la vitalité du centre-ville montréalais ?",
    "answerBullets": [
      "Référence à l'étude de benchmarking d'attractivité",
      "Filtres de transférabilité",
      "Politique locale"
    ],
    "fullScript": "Ouverture : « Comment synthétisez-vous les meilleures pratiques mondiales pour la vitalité du centre-ville montréalais  ? » — Voici comment je le cadre pour Volume10.\n\n1. Référence à l'étude de benchmarking d'attractivité\n2. Filtres de transférabilité\n3. Politique locale\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Pilier Intelligence"
    ],
    "relatedCaseStudy": "Le retour au bureau — Travail en présentiel au Québec"
  },
  {
    "id": "q039",
    "categoryId": "case-style",
    "question": "Cas : le CUSM demande d'accélérer l'adoption de l'innovation sur les sites — vos 2 premières semaines ?",
    "answerBullets": [
      "Entrevues parties prenantes, audit du portefeuille d'innovation",
      "Mémo de diagnostic rapide",
      "Critères de pilote"
    ],
    "fullScript": "Ouverture : « Cas : le CUSM demande d'accélérer l'adoption de l'innovation sur les sites — vos 2 premières semaines  ? » — Voici comment je le cadre pour Volume10.\n\n1. Entrevues parties prenantes, audit du portefeuille d'innovation\n2. Mémo de diagnostic rapide\n3. Critères de pilote\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Études de cas et mandats"
    ],
    "relatedCaseStudy": "Quantum Ahead",
    "context": "Étude de cas — tester lecture mandats Volume Dix",
    "interviewerVariants": [
      "Quel mandat Volume Dix citeriez-vous pour un client santé ?"
    ],
    "difficulty": "standard"
  },
  {
    "id": "q040",
    "categoryId": "case-style",
    "question": "Cas : la Ville veut revitaliser Griffintown — quelles questions posez-vous en premier ?",
    "answerBullets": [
      "Économique, social, mobilité, patrimoine",
      "Équilibre promoteurs vs communauté",
      "Gains par phases"
    ],
    "fullScript": "Ouverture : « Cas : la Ville veut revitaliser Griffintown — quelles questions posez-vous en premier  ? » — Voici comment je le cadre pour Volume10.\n\n1. Économique, social, mobilité, patrimoine\n2. Équilibre promoteurs vs communauté\n3. Gains par phases\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Études de cas et mandats"
    ],
    "relatedCaseStudy": "Plan stratégique Place des Arts 2023–2027"
  },
  {
    "id": "q041",
    "categoryId": "case-style",
    "question": "Cas : Transplant Québec a besoin du plan 2023–2027 — comment structurez-vous l'approche ?",
    "answerBullets": [
      "Alignement mission, ateliers parties prenantes",
      "Scénarios de demande",
      "Feuille de route de mise en œuvre"
    ],
    "fullScript": "Ouverture : « Cas : Transplant Québec a besoin du plan 2023–2027 — comment structurez-vous l'approche  ? » — Voici comment je le cadre pour Volume10.\n\n1. Alignement mission, ateliers parties prenantes\n2. Scénarios de demande\n3. Feuille de route de mise en œuvre\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Études de cas et mandats"
    ]
  },
  {
    "id": "q042",
    "categoryId": "case-style",
    "question": "Cas : l'engagement des ménages vulnérables d'un distributeur d'énergie stagne — diagnostic.",
    "answerBullets": [
      "Barrières : confiance, langue, bureaucratie",
      "Partenaires de canal",
      "Repenser le parcours"
    ],
    "fullScript": "Ouverture : « Cas : l'engagement des ménages vulnérables d'un distributeur d'énergie stagne — diagnostic. ? » — Voici comment je le cadre pour Volume10.\n\n1. Barrières : confiance, langue, bureaucratie\n2. Partenaires de canal\n3. Repenser le parcours\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Études de cas et mandats"
    ]
  },
  {
    "id": "q043",
    "categoryId": "case-style",
    "question": "Cas : plan directeur d'innovation CHU de Québec — 3 livrables prioritaires ?",
    "answerBullets": [
      "Gouvernance, portefeuille, indicateurs",
      "Alignement clinique + administratif",
      "Carte de financement"
    ],
    "fullScript": "Ouverture : « Cas : plan directeur d'innovation CHU de Québec — 3 livrables prioritaires  ? » — Voici comment je le cadre pour Volume10.\n\n1. Gouvernance, portefeuille, indicateurs\n2. Alignement clinique + administratif\n3. Carte de financement\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Études de cas et mandats"
    ]
  },
  {
    "id": "q044",
    "categoryId": "case-style",
    "question": "Cas : croissance du secteur viticole québécois — comment dimensionnez l'opportunité ?",
    "answerBullets": [
      "Marché, réglementation, lien tourisme",
      "Ensemble concurrentiel",
      "Options de mise en marché"
    ],
    "fullScript": "Ouverture : « Cas : croissance du secteur viticole québécois — comment dimensionnez l'opportunité  ? » — Voici comment je le cadre pour Volume10.\n\n1. Marché, réglementation, lien tourisme\n2. Ensemble concurrentiel\n3. Options de mise en marché\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Études de cas et mandats"
    ]
  },
  {
    "id": "q045",
    "categoryId": "case-style",
    "question": "Cas : plan directeur TI pour un organisme public — équilibre patrimoine et infonuagique ?",
    "answerBullets": [
      "Risque, coût, talents",
      "Migration par phases",
      "Cybersécurité"
    ],
    "fullScript": "Ouverture : « Cas : plan directeur TI pour un organisme public — équilibre patrimoine et infonuagique  ? » — Voici comment je le cadre pour Volume10.\n\n1. Risque, coût, talents\n2. Migration par phases\n3. Cybersécurité\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Études de cas et mandats"
    ]
  },
  {
    "id": "q046",
    "categoryId": "case-style",
    "question": "Cas : encombrement minimal sur les chantiers — quels indicateurs comptent ?",
    "answerBullets": [
      "Temps, coût, perturbation communautaire",
      "Adoption de l'innovation",
      "Incitatifs entrepreneurs"
    ],
    "fullScript": "Ouverture : « Cas : encombrement minimal sur les chantiers — quels indicateurs comptent  ? » — Voici comment je le cadre pour Volume10.\n\n1. Temps, coût, perturbation communautaire\n2. Adoption de l'innovation\n3. Incitatifs entrepreneurs\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Études de cas et mandats"
    ]
  },
  {
    "id": "q047",
    "categoryId": "case-style",
    "question": "Cas : positionnement CCOMTL avec Santé Québec — carte des parties prenantes ?",
    "answerBullets": [
      "Cliniciens, ministère, patients",
      "Proposition de valeur",
      "Preuves"
    ],
    "fullScript": "Ouverture : « Cas : positionnement CCOMTL avec Santé Québec — carte des parties prenantes  ? » — Voici comment je le cadre pour Volume10.\n\n1. Cliniciens, ministère, patients\n2. Proposition de valeur\n3. Preuves\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Études de cas et mandats"
    ]
  },
  {
    "id": "q048",
    "categoryId": "case-style",
    "question": "Cas : plan stratégique Place des Arts — en quoi les indicateurs culturels diffèrent ?",
    "answerBullets": [
      "Fréquentation, communauté, mix de financement",
      "Objectifs artistiques vs commerciaux",
      "Partenaires"
    ],
    "fullScript": "Ouverture : « Cas : plan stratégique Place des Arts — en quoi les indicateurs culturels diffèrent  ? » — Voici comment je le cadre pour Volume10.\n\n1. Fréquentation, communauté, mix de financement\n2. Objectifs artistiques vs commerciaux\n3. Partenaires\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Études de cas et mandats"
    ]
  },
  {
    "id": "q049",
    "categoryId": "case-style",
    "question": "Estimation : combien de consultants une firme de 40 personnes affecte-t-elle à un mandat de 2 M$ ?",
    "answerBullets": [
      "Composition d'équipe, modèle de levier",
      "Supervision associée",
      "Marge de risque"
    ],
    "fullScript": "Ouverture : « Estimation : combien de consultants une firme de 40 personnes affecte-t-elle à un mandat de 2 M$  ? » — Voici comment je le cadre pour Volume10.\n\n1. Composition d'équipe, modèle de levier\n2. Supervision associée\n3. Marge de risque\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Études de cas et mandats"
    ]
  },
  {
    "id": "q050",
    "categoryId": "case-style",
    "question": "Vous avez 24 h pour préparer une offre pour un nouveau client santé — plan.",
    "answerBullets": [
      "Hypothèse, 3 insights de données publiques",
      "Phase 0 proposée",
      "Équipe + échéancier"
    ],
    "fullScript": "Ouverture : « Vous avez 24 h pour préparer une offre pour un nouveau client santé — plan. ? » — Voici comment je le cadre pour Volume10.\n\n1. Hypothèse, 3 insights de données publiques\n2. Phase 0 proposée\n3. Équipe + échéancier\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Études de cas et mandats"
    ]
  },
  {
    "id": "q051",
    "categoryId": "sectors",
    "question": "Infrastructure et construction : quels thèmes d'innovation comptent au Québec ?",
    "answerBullets": [
      "Chantiers, approvisionnement, durabilité",
      "Référence à l'étude encombrement minimal",
      "Cycles d'infrastructure publique"
    ],
    "fullScript": "Ouverture : « Infrastructure et construction : quels thèmes d'innovation comptent au Québec  ? » — Voici comment je le cadre pour Volume10.\n\n1. Chantiers, approvisionnement, durabilité\n2. Référence à l'étude encombrement minimal\n3. Cycles d'infrastructure publique\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Connaissance sectorielle"
    ]
  },
  {
    "id": "q052",
    "categoryId": "sectors",
    "question": "Santé numérique et soins connectés : principaux risques de mise en œuvre ?",
    "answerBullets": [
      "Flux clinique, gestion du changement, interopérabilité",
      "Loi sur la protection des renseignements personnels",
      "Équité"
    ],
    "fullScript": "Ouverture : « Santé numérique et soins connectés : principaux risques de mise en œuvre  ? » — Voici comment je le cadre pour Volume10.\n\n1. Flux clinique, gestion du changement, interopérabilité\n2. Loi sur la protection des renseignements personnels\n3. Équité\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Connaissance sectorielle"
    ]
  },
  {
    "id": "q053",
    "categoryId": "sectors",
    "question": "Technologie et ingénierie : comment conseillez-vous scale-ups vs grandes entreprises ?",
    "answerBullets": [
      "Efficacité du capital vs gouvernance",
      "Talents",
      "Partenariats"
    ],
    "fullScript": "Ouverture : « Technologie et ingénierie : comment conseillez-vous scale-ups vs grandes entreprises  ? » — Voici comment je le cadre pour Volume10.\n\n1. Efficacité du capital vs gouvernance\n2. Talents\n3. Partenariats\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Connaissance sectorielle"
    ]
  },
  {
    "id": "q054",
    "categoryId": "sectors",
    "question": "Énergie et mobilité : tendances touchant les programmes publics ?",
    "answerBullets": [
      "Électrification, équité, financement",
      "Engagement des ménages vulnérables",
      "Mesure"
    ],
    "fullScript": "Ouverture : « Énergie et mobilité : tendances touchant les programmes publics  ? » — Voici comment je le cadre pour Volume10.\n\n1. Électrification, équité, financement\n2. Engagement des ménages vulnérables\n3. Mesure\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Connaissance sectorielle"
    ]
  },
  {
    "id": "q055",
    "categoryId": "sectors",
    "question": "Développement socioéconomique : comment mesurez-vous le succès ?",
    "answerBullets": [
      "Emplois, inclusion, impact régional",
      "Horizons longs",
      "Sensibilité politique"
    ],
    "fullScript": "Ouverture : « Développement socioéconomique : comment mesurez-vous le succès  ? » — Voici comment je le cadre pour Volume10.\n\n1. Emplois, inclusion, impact régional\n2. Horizons longs\n3. Sensibilité politique\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Connaissance sectorielle"
    ]
  },
  {
    "id": "q056",
    "categoryId": "sectors",
    "question": "Savoir et éducation : planification stratégique pour les cégeps — nuances ?",
    "answerBullets": [
      "Étudiants, personnel, gouvernement",
      "Plans de réussite",
      "Référence au cas collégial"
    ],
    "fullScript": "Ouverture : « Savoir et éducation : planification stratégique pour les cégeps — nuances  ? » — Voici comment je le cadre pour Volume10.\n\n1. Étudiants, personnel, gouvernement\n2. Plans de réussite\n3. Référence au cas collégial\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Connaissance sectorielle"
    ]
  },
  {
    "id": "q057",
    "categoryId": "sectors",
    "question": "Ville et immobilier : vitalité du centre-ville — quels leviers ?",
    "answerBullets": [
      "Usage mixte, événements, sécurité, transport",
      "Benchmarks mondiaux",
      "Parties prenantes locales"
    ],
    "fullScript": "Ouverture : « Ville et immobilier : vitalité du centre-ville — quels leviers  ? » — Voici comment je le cadre pour Volume10.\n\n1. Usage mixte, événements, sécurité, transport\n2. Benchmarks mondiaux\n3. Parties prenantes locales\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Connaissance sectorielle"
    ]
  },
  {
    "id": "q058",
    "categoryId": "sectors",
    "question": "Culture et hôtellerie : stratégies de reprise post-pandémie ?",
    "answerBullets": [
      "Développement d'audiences, événements hybrides",
      "Diversification du financement",
      "Modèles Place des Arts"
    ],
    "fullScript": "Ouverture : « Culture et hôtellerie : stratégies de reprise post-pandémie  ? » — Voici comment je le cadre pour Volume10.\n\n1. Développement d'audiences, événements hybrides\n2. Diversification du financement\n3. Modèles Place des Arts\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Connaissance sectorielle"
    ]
  },
  {
    "id": "q059",
    "categoryId": "sectors",
    "question": "Comment restez-vous à jour sur huit secteurs sans rester superficiel ?",
    "answerBullets": [
      "Expertise en T + recherche rapide",
      "Habitudes du pilier Intelligence",
      "Réseau d'experts"
    ],
    "fullScript": "Ouverture : « Comment restez-vous à jour sur huit secteurs sans rester superficiel  ? » — Voici comment je le cadre pour Volume10.\n\n1. Expertise en T + recherche rapide\n2. Habitudes du pilier Intelligence\n3. Réseau d'experts\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Connaissance sectorielle"
    ]
  },
  {
    "id": "q060",
    "categoryId": "sectors",
    "question": "Quel secteur mèneriez-vous ici — et lequel apprendriez-vous vite ?",
    "answerBullets": [
      "Force honnête + plan d'apprentissage",
      "Combiner avec l'écart du portefeuille Volume10",
      "Montée en charge à 90 jours"
    ],
    "fullScript": "Ouverture : « Quel secteur mèneriez-vous ici — et lequel apprendriez-vous vite  ? » — Voici comment je le cadre pour Volume10.\n\n1. Force honnête + plan d'apprentissage\n2. Combiner avec l'écart du portefeuille Volume10\n3. Montée en charge à 90 jours\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Connaissance sectorielle"
    ]
  },
  {
    "id": "q061",
    "categoryId": "behavioral",
    "question": "Parlez-nous d'une fois où vous avez dirigé sans autorité formelle.",
    "answerBullets": [
      "STAR",
      "Mesure de résultat",
      "Ce que vous referiez"
    ],
    "fullScript": "Ouverture : « Parlez-nous d'une fois où vous avez dirigé sans autorité formelle. ? » — Voici comment je le cadre pour Volume10.\n\n1. STAR\n2. Mesure de résultat\n3. Ce que vous referiez\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Comportemental (STAR)"
    ],
    "bilingualRequired": true,
    "context": "Comportemental — même question que candidature Volume Dix",
    "interviewerVariants": [
      "Racontez un projet initié par vous-même — pas assigné.",
      "Et si le client n'avait pas adopté Smartsheet ?"
    ],
    "difficulty": "followUp"
  },
  {
    "id": "q062",
    "categoryId": "behavioral",
    "question": "Décrivez un projet raté et ce que vous en avez tiré.",
    "answerBullets": [
      "Responsabilité",
      "Relation client préservée ?",
      "Correction de processus"
    ],
    "fullScript": "Ouverture : « Décrivez un projet raté et ce que vous en avez tiré. ? » — Voici comment je le cadre pour Volume10.\n\n1. Responsabilité\n2. Relation client préservée ?\n3. Correction de processus\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Comportemental (STAR)"
    ],
    "bilingualRequired": true
  },
  {
    "id": "q063",
    "categoryId": "behavioral",
    "question": "Conflit avec un collègue sur la méthodologie — résolution ?",
    "answerBullets": [
      "Données + intérêt client",
      "Compromis ou escalade",
      "Relation après coup"
    ],
    "fullScript": "Ouverture : « Conflit avec un collègue sur la méthodologie — résolution  ? » — Voici comment je le cadre pour Volume10.\n\n1. Données + intérêt client\n2. Compromis ou escalade\n3. Relation après coup\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Comportemental (STAR)"
    ],
    "bilingualRequired": true
  },
  {
    "id": "q064",
    "categoryId": "behavioral",
    "question": "Échéance serrée — comment avez-vous priorisé ?",
    "answerBullets": [
      "Impact vs effort",
      "Communication au client",
      "Garde-fous qualité"
    ],
    "fullScript": "Ouverture : « Échéance serrée — comment avez-vous priorisé  ? » — Voici comment je le cadre pour Volume10.\n\n1. Impact vs effort\n2. Communication au client\n3. Garde-fous qualité\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Comportemental (STAR)"
    ],
    "bilingualRequired": true
  },
  {
    "id": "q065",
    "categoryId": "behavioral",
    "question": "Rétroaction qui a changé votre style de conseil.",
    "answerBullets": [
      "Citation précise",
      "Changement de comportement",
      "Résultat"
    ],
    "fullScript": "Ouverture : « Rétroaction qui a changé votre style de conseil. ? » — Voici comment je le cadre pour Volume10.\n\n1. Citation précise\n2. Changement de comportement\n3. Résultat\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Comportemental (STAR)"
    ],
    "bilingualRequired": true
  },
  {
    "id": "q066",
    "categoryId": "behavioral",
    "question": "Situation exigeant une prise de position éthique.",
    "answerBullets": [
      "Principe",
      "Comment vous avez dit non",
      "Alternative proposée"
    ],
    "fullScript": "Ouverture : « Situation exigeant une prise de position éthique. ? » — Voici comment je le cadre pour Volume10.\n\n1. Principe\n2. Comment vous avez dit non\n3. Alternative proposée\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Comportemental (STAR)"
    ],
    "bilingualRequired": true
  },
  {
    "id": "q067",
    "categoryId": "behavioral",
    "question": "Gestion d'un sponsor exécutif difficile.",
    "answerBullets": [
      "Empathie, limites, victoires",
      "Décisions documentées",
      "Escalade si nécessaire"
    ],
    "fullScript": "Ouverture : « Gestion d'un sponsor exécutif difficile. ? » — Voici comment je le cadre pour Volume10.\n\n1. Empathie, limites, victoires\n2. Décisions documentées\n3. Escalade si nécessaire\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Comportemental (STAR)"
    ],
    "bilingualRequired": true
  },
  {
    "id": "q068",
    "categoryId": "behavioral",
    "question": "Apprendre à pêcher vs faire le travail pour le client.",
    "answerBullets": [
      "Renforcement des capacités",
      "Modèles, coaching",
      "Quand prendre du recul"
    ],
    "fullScript": "Ouverture : « Apprendre à pêcher vs faire le travail pour le client. ? » — Voici comment je le cadre pour Volume10.\n\n1. Renforcement des capacités\n2. Modèles, coaching\n3. Quand prendre du recul\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Comportemental (STAR)"
    ],
    "bilingualRequired": true
  },
  {
    "id": "q069",
    "categoryId": "behavioral",
    "question": "Équipe multiculturelle — ajustement de communication.",
    "answerBullets": [
      "Exemples Grèce + UE + Canada à distance",
      "Écoute active",
      "Synthèses écrites"
    ],
    "fullScript": "Ouverture : « Équipe multiculturelle — ajustement de communication. ? » — Voici comment je le cadre pour Volume10.\n\n1. Exemples Grèce + UE + Canada à distance\n2. Écoute active\n3. Synthèses écrites\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Comportemental (STAR)"
    ],
    "bilingualRequired": true
  },
  {
    "id": "q070",
    "categoryId": "behavioral",
    "question": "Livrable dont vous êtes le plus fier — pourquoi ?",
    "answerBullets": [
      "Impact client",
      "Crédit à l'équipe",
      "Orientation action Volume10"
    ],
    "fullScript": "Ouverture : « Livrable dont vous êtes le plus fier — pourquoi  ? » — Voici comment je le cadre pour Volume10.\n\n1. Impact client\n2. Crédit à l'équipe\n3. Orientation action Volume10\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Comportemental (STAR)"
    ],
    "bilingualRequired": true
  },
  {
    "id": "q071",
    "categoryId": "relocation",
    "question": "L'offre exige 100 % en présentiel au Vieux-Montréal — pourquoi croire à votre engagement depuis la Grèce ?",
    "answerBullets": [
      "Citer l'annonce : présentiel non négociable pour vous — proximité boutique voulue",
      "Échéancier : départ Deloitte fin juillet, visa/logement en cours, passation équipe",
      "Parcours mobilité Taza→Fès→Marrakech→Athènes — pas première relocalisation"
    ],
    "fullScript": "Ouverture : « L'offre exige 100 % en présentiel au Vieux-Montréal — pourquoi croire à votre engagement depuis la Grèce  ? » — Voici comment je le cadre pour Volume10.\n\n1. Citer l'annonce : présentiel non négociable pour vous — proximité boutique voulue\n2. Échéancier : départ Deloitte fin juillet, visa/logement en cours, passation équipe\n3. Parcours mobilité Taza→Fès→Marrakech→Athènes — pas première relocalisation\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Relocalisation et présence sur site"
    ],
    "bilingualRequired": true,
    "context": "Recruteur — mobilité sensible",
    "interviewerVariants": [
      "Pourquoi quitter la Grèce maintenant ?",
      "N'est-ce pas un risque de recruter quelqu'un en transition visa ?"
    ],
    "difficulty": "stress"
  },
  {
    "id": "q072",
    "categoryId": "relocation",
    "question": "Quel est votre plan d'autorisation de travail pour le Canada ?",
    "answerBullets": [
      "Entrée express / catégories de permis recherchées",
      "Ouverture à une EIM appuyée par l'employeur",
      "Échéancier honnête — ne pas bluffer"
    ],
    "fullScript": "Ouverture : « Quel est votre plan d'autorisation de travail pour le Canada  ? » — Voici comment je le cadre pour Volume10.\n\n1. Entrée express / catégories de permis recherchées\n2. Ouverture à une EIM appuyée par l'employeur\n3. Échéancier honnête — ne pas bluffer\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Relocalisation et présence sur site"
    ],
    "bilingualRequired": true
  },
  {
    "id": "q073",
    "categoryId": "relocation",
    "question": "Pourquoi quitter la Grèce pour une boutique au Canada maintenant ?",
    "answerBullets": [
      "Thèse de carrière : secteurs servis par Volume10",
      "Qualité des mandats vs marché local",
      "Préparation personnelle — fuir vs aller vers"
    ],
    "fullScript": "Ouverture : « Pourquoi quitter la Grèce pour une boutique au Canada maintenant  ? » — Voici comment je le cadre pour Volume10.\n\n1. Thèse de carrière : secteurs servis par Volume10\n2. Qualité des mandats vs marché local\n3. Préparation personnelle — fuir vs aller vers\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Relocalisation et présence sur site"
    ]
  },
  {
    "id": "q074",
    "categoryId": "relocation",
    "question": "Comment gérerez-vous l'éloignement de la famille — risque de départ ?",
    "answerBullets": [
      "Plan de soutien",
      "Mentalité période d'essai",
      "Signaux d'intention long terme"
    ],
    "fullScript": "Ouverture : « Comment gérerez-vous l'éloignement de la famille — risque de départ  ? » — Voici comment je le cadre pour Volume10.\n\n1. Plan de soutien\n2. Mentalité période d'essai\n3. Signaux d'intention long terme\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Relocalisation et présence sur site"
    ]
  },
  {
    "id": "q075",
    "categoryId": "relocation",
    "question": "Avez-vous travaillé avec des clients nord-américains à distance ? Preuves.",
    "answerBullets": [
      "Fuseaux horaires gérés",
      "Exemples de communication interculturelle",
      "Références si possible"
    ],
    "fullScript": "Ouverture : « Avez-vous travaillé avec des clients nord-américains à distance  ? » — Voici comment je le cadre pour Volume10.\n\n1. Fuseaux horaires gérés\n2. Exemples de communication interculturelle\n3. Références si possible\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Relocalisation et présence sur site"
    ],
    "context": "Recruteur — présentiel Vieux-Montréal (exigence offre)",
    "interviewerVariants": [
      "Le 100 % présentiel vous convient-il vraiment ?",
      "Avez-vous déjà un plan logement / arrivée ?"
    ],
    "difficulty": "stress"
  },
  {
    "id": "q076",
    "categoryId": "relocation",
    "question": "Niveau de français — actuel et plan à 6 mois ?",
    "answerBullets": [
      "Niveau CECR honnête",
      "Cours, partenaires de conversation, médias québécois",
      "Engagement croissance en français face au client"
    ],
    "fullScript": "Ouverture : « Niveau de français — actuel et plan à 6 mois  ? » — Voici comment je le cadre pour Volume10.\n\n1. Niveau CECR honnête\n2. Cours, partenaires de conversation, médias québécois\n3. Engagement croissance en français face au client\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Relocalisation et présence sur site"
    ]
  },
  {
    "id": "q077",
    "categoryId": "relocation",
    "question": "90 premiers jours sur site — que faites-vous avant le jour 1 ?",
    "answerBullets": [
      "Quartiers pour le logement, réseau conseil montréalais",
      "Lire les rapports Intelligence",
      "Observer l'équipe sur un mandat en cours"
    ],
    "fullScript": "Ouverture : « 90 premiers jours sur site — que faites-vous avant le jour 1  ? » — Voici comment je le cadre pour Volume10.\n\n1. Quartiers pour le logement, réseau conseil montréalais\n2. Lire les rapports Intelligence\n3. Observer l'équipe sur un mandat en cours\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Relocalisation et présence sur site"
    ]
  },
  {
    "id": "q078",
    "categoryId": "relocation",
    "question": "Comment réagissez-vous si nous avons besoin de vous en atelier client dans les 2 semaines suivant l'embauche ?",
    "answerBullets": [
      "Passeport prêt, flexibilité",
      "Préparation à distance puis vol — logistique réaliste",
      "Pas d'hésitation"
    ],
    "fullScript": "Ouverture : « Comment réagissez-vous si nous avons besoin de vous en atelier client dans les 2 semaines suivant l'embauche  ? » — Voici comment je le cadre pour Volume10.\n\n1. Passeport prêt, flexibilité\n2. Préparation à distance puis vol — logistique réaliste\n3. Pas d'hésitation\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Relocalisation et présence sur site"
    ]
  },
  {
    "id": "q079",
    "categoryId": "relocation",
    "question": "Coût de vie : les discussions de rémunération vous distrairont-elles ?",
    "answerBullets": [
      "Adéquation au rôle d'abord",
      "Recherche des fourchettes montréalaises",
      "Au-dessus du marché — valeur apportée"
    ],
    "fullScript": "Ouverture : « Coût de vie : les discussions de rémunération vous distrairont-elles  ? » — Voici comment je le cadre pour Volume10.\n\n1. Adéquation au rôle d'abord\n2. Recherche des fourchettes montréalaises\n3. Au-dessus du marché — valeur apportée\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Relocalisation et présence sur site"
    ]
  },
  {
    "id": "q080",
    "categoryId": "relocation",
    "question": "Que savez-vous du marché du talent conseil à Montréal ?",
    "answerBullets": [
      "Concurrence pour les seniors bilingues",
      "Vous vous différenciez : international + secteur X",
      "Loyauté à la mission boutique"
    ],
    "fullScript": "Ouverture : « Que savez-vous du marché du talent conseil à Montréal  ? » — Voici comment je le cadre pour Volume10.\n\n1. Concurrence pour les seniors bilingues\n2. Vous vous différenciez : international + secteur X\n3. Loyauté à la mission boutique\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Relocalisation et présence sur site"
    ]
  },
  {
    "id": "q081",
    "categoryId": "relocation",
    "question": "Attentes hybrides — de quoi avez-vous besoin vs ce dont nous avons besoin ?",
    "answerBullets": [
      "Présence par défaut pour la cohésion d'équipe",
      "Déplacements clients Québec si requis",
      "Limites claires"
    ],
    "fullScript": "Ouverture : « Attentes hybrides — de quoi avez-vous besoin vs ce dont nous avons besoin  ? » — Voici comment je le cadre pour Volume10.\n\n1. Présence par défaut pour la cohésion d'équipe\n2. Déplacements clients Québec si requis\n3. Limites claires\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Relocalisation et présence sur site"
    ]
  },
  {
    "id": "q082",
    "categoryId": "relocation",
    "question": "Pourquoi Volume10 plutôt qu'une firme globale à Toronto qui pourrait sponsoriser le visa plus vite ?",
    "answerBullets": [
      "Impact boutique, secteurs, adéquation culture « donner de l'espace »",
      "Proximité des associés",
      "Ne pas les utiliser comme plan B"
    ],
    "fullScript": "Ouverture : « Pourquoi Volume10 plutôt qu'une firme globale à Toronto qui pourrait sponsoriser le visa plus vite  ? » — Voici comment je le cadre pour Volume10.\n\n1. Impact boutique, secteurs, adéquation culture « donner de l'espace »\n2. Proximité des associés\n3. Ne pas les utiliser comme plan B\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Relocalisation et présence sur site"
    ]
  },
  {
    "id": "q083",
    "categoryId": "small-team",
    "question": "Notre équipe compte moins de 50 personnes — comment prospérez-vous sans le bench d'une grande firme ?",
    "answerBullets": [
      "Généraliste + expertise pointue",
      "Bâtir votre propre réseau d'experts",
      "Documenter les méthodes pour réutilisation"
    ],
    "fullScript": "Ouverture : « Notre équipe compte moins de 50 personnes — comment prospérez-vous sans le bench d'une grande firme  ? » — Voici comment je le cadre pour Volume10.\n\n1. Généraliste + expertise pointue\n2. Bâtir votre propre réseau d'experts\n3. Documenter les méthodes pour réutilisation\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Petite équipe (<50)"
    ],
    "context": "Petite équipe boutique",
    "interviewerVariants": [
      "Comment gérez-vous l'ambiguïté sans structure Big Four ?"
    ],
    "difficulty": "standard"
  },
  {
    "id": "q084",
    "categoryId": "small-team",
    "question": "Décrivez le port de plusieurs chapeaux sur un mandat.",
    "answerBullets": [
      "GP + analyste + facilitateur",
      "Contrôle qualité",
      "Exemple"
    ],
    "fullScript": "Ouverture : « Décrivez le port de plusieurs chapeaux sur un mandat. ? » — Voici comment je le cadre pour Volume10.\n\n1. GP + analyste + facilitateur\n2. Contrôle qualité\n3. Exemple\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Petite équipe (<50)"
    ]
  },
  {
    "id": "q085",
    "categoryId": "small-team",
    "question": "Face au client dès la première semaine — niveau de confort ?",
    "answerBullets": [
      "Rituels de préparation",
      "Présence exécutive",
      "Demander du coaching"
    ],
    "fullScript": "Ouverture : « Face au client dès la première semaine — niveau de confort  ? » — Voici comment je le cadre pour Volume10.\n\n1. Rituels de préparation\n2. Présence exécutive\n3. Demander du coaching\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Petite équipe (<50)"
    ]
  },
  {
    "id": "q086",
    "categoryId": "small-team",
    "question": "Comment éviter l'épuisement quand tout le monde est à bout ?",
    "answerBullets": [
      "Priorisation, dire non avec alternatives",
      "Habitudes de récupération",
      "Signaler les risques tôt"
    ],
    "fullScript": "Ouverture : « Comment éviter l'épuisement quand tout le monde est à bout  ? » — Voici comment je le cadre pour Volume10.\n\n1. Priorisation, dire non avec alternatives\n2. Habitudes de récupération\n3. Signaler les risques tôt\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Petite équipe (<50)"
    ]
  },
  {
    "id": "q087",
    "categoryId": "small-team",
    "question": "Bâtir de la PI pour une petite firme — que contribueriez-vous ?",
    "answerBullets": [
      "Modèles, primers sectoriels, rédactions de cas",
      "Sujets Intelligence",
      "Mentorat juniors si applicable"
    ],
    "fullScript": "Ouverture : « Bâtir de la PI pour une petite firme — que contribueriez-vous  ? » — Voici comment je le cadre pour Volume10.\n\n1. Modèles, primers sectoriels, rédactions de cas\n2. Sujets Intelligence\n3. Mentorat juniors si applicable\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Petite équipe (<50)"
    ]
  },
  {
    "id": "q088",
    "categoryId": "small-team",
    "question": "Comment obtenir la rétroaction des associés dans une boutique plate ?",
    "answerBullets": [
      "Points réguliers",
      "Revue de brouillons",
      "Rétro après les jalons"
    ],
    "fullScript": "Ouverture : « Comment obtenir la rétroaction des associés dans une boutique plate  ? » — Voici comment je le cadre pour Volume10.\n\n1. Points réguliers\n2. Revue de brouillons\n3. Rétro après les jalons\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Petite équipe (<50)"
    ]
  },
  {
    "id": "q089",
    "categoryId": "small-team",
    "question": "Vendre du travail de suivi sans être « vendeur ».",
    "answerBullets": [
      "Valeur livrée visible",
      "Prochaine hypothèse cadrée",
      "Succès client d'abord"
    ],
    "fullScript": "Ouverture : « Vendre du travail de suivi sans être « vendeur ». ? » — Voici comment je le cadre pour Volume10.\n\n1. Valeur livrée visible\n2. Prochaine hypothèse cadrée\n3. Succès client d'abord\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Petite équipe (<50)"
    ]
  },
  {
    "id": "q090",
    "categoryId": "small-team",
    "question": "Autonomie vs demander de l'aide — équilibre ?",
    "answerBullets": [
      "Quand décider seul",
      "Quand escalader",
      "Exemple de chaque"
    ],
    "fullScript": "Ouverture : « Autonomie vs demander de l'aide — équilibre  ? » — Voici comment je le cadre pour Volume10.\n\n1. Quand décider seul\n2. Quand escalader\n3. Exemple de chaque\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Petite équipe (<50)"
    ]
  },
  {
    "id": "q091",
    "categoryId": "compensation",
    "question": "Quelles sont vos attentes salariales pour Montréal ?",
    "answerBullets": [
      "Fourchette recherchée pour le niveau consultant",
      "Rémunération totale : base + prime si applicable",
      "Flexibilité si la portée du rôle le justifie"
    ],
    "fullScript": "Ouverture : « Quelles sont vos attentes salariales pour Montréal  ? » — Voici comment je le cadre pour Volume10.\n\n1. Fourchette recherchée pour le niveau consultant\n2. Rémunération totale : base + prime si applicable\n3. Flexibilité si la portée du rôle le justifie\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Rémunération"
    ]
  },
  {
    "id": "q092",
    "categoryId": "compensation",
    "question": "Ils paient légèrement au-dessus du marché — comment en discuter sans vous sous-vendre ?",
    "answerBullets": [
      "Ancrage sur la valeur et la portée",
      "Demander la fourchette, pas seulement le chiffre",
      "Au-delà du salaire : apprentissage, mandats, soutien visa"
    ],
    "fullScript": "Ouverture : « Ils paient légèrement au-dessus du marché — comment en discuter sans vous sous-vendre  ? » — Voici comment je le cadre pour Volume10.\n\n1. Ancrage sur la valeur et la portée\n2. Demander la fourchette, pas seulement le chiffre\n3. Au-delà du salaire : apprentissage, mandats, soutien visa\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Rémunération"
    ]
  },
  {
    "id": "q093",
    "categoryId": "compensation",
    "question": "Comment réagissez-vous à « vous êtes en Grèce donc on paie moins » ?",
    "answerBullets": [
      "Sur site = marché du travail local",
      "Refuser poliment l'arbitrage géographique",
      "Focus sur les résultats"
    ],
    "fullScript": "Ouverture : « Comment réagissez-vous à « vous êtes en Grèce donc on paie moins »  ? » — Voici comment je le cadre pour Volume10.\n\n1. Sur site = marché du travail local\n2. Refuser poliment l'arbitrage géographique\n3. Focus sur les résultats\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Rémunération"
    ]
  },
  {
    "id": "q094",
    "categoryId": "compensation",
    "question": "Avantages et soutien à la relocalisation — qu'est-ce qui compte pour vous ?",
    "answerBullets": [
      "Soutien juridique immigration",
      "Allocation de relocalisation réaliste",
      "Transition assurance maladie"
    ],
    "fullScript": "Ouverture : « Avantages et soutien à la relocalisation — qu'est-ce qui compte pour vous  ? » — Voici comment je le cadre pour Volume10.\n\n1. Soutien juridique immigration\n2. Allocation de relocalisation réaliste\n3. Transition assurance maladie\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Rémunération"
    ],
    "context": "Profil atypique — l'offre l'encourage",
    "interviewerVariants": [
      "Vous n'avez pas fait HEC ou McKinsey — pourquoi vous quand même ?",
      "Qu'apporte un parcours compliance à du conseil exécutif ?"
    ],
    "difficulty": "stress"
  },
  {
    "id": "q095",
    "categoryId": "compensation",
    "question": "Quand négocier vs quand accepter ?",
    "answerBullets": [
      "Après adéquation mutuelle claire",
      "Étape de l'offre écrite",
      "Plusieurs dimensions, pas seulement l'argent"
    ],
    "fullScript": "Ouverture : « Quand négocier vs quand accepter  ? » — Voici comment je le cadre pour Volume10.\n\n1. Après adéquation mutuelle claire\n2. Étape de l'offre écrite\n3. Plusieurs dimensions, pas seulement l'argent\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Rémunération"
    ]
  },
  {
    "id": "q096",
    "categoryId": "curveball",
    "question": "Si nous ne vous embauchons pas, que devrions-nous améliorer dans notre processus ?",
    "answerBullets": [
      "Réflexion constructive, pas amertume",
      "Montre l'esprit consultant",
      "Sincère"
    ],
    "fullScript": "Ouverture : « Si nous ne vous embauchons pas, que devrions-nous améliorer dans notre processus  ? » — Voici comment je le cadre pour Volume10.\n\n1. Réflexion constructive, pas amertume\n2. Montre l'esprit consultant\n3. Sincère\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Questions difficiles / pièges"
    ],
    "context": "Question piège — cohérence parcours",
    "interviewerVariants": [
      "Pourquoi Volume Dix et pas rester chez Deloitte ?"
    ],
    "difficulty": "stress"
  },
  {
    "id": "q097",
    "categoryId": "curveball",
    "question": "Vendez-moi un stylo — mais pour la marque Volume10.",
    "answerBullets": [
      "Métaphore « donner de l'espace aux idées »",
      "Pas des caractéristiques commoditisées",
      "Spécifique au client"
    ],
    "fullScript": "Ouverture : « Vendez-moi un stylo — mais pour la marque Volume10. ? » — Voici comment je le cadre pour Volume10.\n\n1. Métaphore « donner de l'espace aux idées »\n2. Pas des caractéristiques commoditisées\n3. Spécifique au client\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Questions difficiles / pièges"
    ]
  },
  {
    "id": "q098",
    "categoryId": "curveball",
    "question": "Quelle question espériez-vous que nous ne posions pas ?",
    "answerBullets": [
      "Honnête + pivot vers une force",
      "Relocalisation ou français si applicable",
      "Bref"
    ],
    "fullScript": "Ouverture : « Quelle question espériez-vous que nous ne posions pas  ? » — Voici comment je le cadre pour Volume10.\n\n1. Honnête + pivot vers une force\n2. Relocalisation ou français si applicable\n3. Bref\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Questions difficiles / pièges"
    ]
  },
  {
    "id": "q099",
    "categoryId": "curveball",
    "question": "Un mot que vos collègues utilisent pour vous décrire — défendez-le.",
    "answerBullets": [
      "Histoires à l'appui",
      "Conscience de soi",
      "Humilité"
    ],
    "fullScript": "Ouverture : « Un mot que vos collègues utilisent pour vous décrire — défendez-le. ? » — Voici comment je le cadre pour Volume10.\n\n1. Histoires à l'appui\n2. Conscience de soi\n3. Humilité\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Questions difficiles / pièges"
    ]
  },
  {
    "id": "q100",
    "categoryId": "curveball",
    "question": "Que feriez-vous le premier mois si les mandats sont calmes ?",
    "answerBullets": [
      "Soutien au développement d'affaires",
      "Contenu Intelligence",
      "Construction méthodologique"
    ],
    "fullScript": "Ouverture : « Que feriez-vous le premier mois si les mandats sont calmes  ? » — Voici comment je le cadre pour Volume10.\n\n1. Soutien au développement d'affaires\n2. Contenu Intelligence\n3. Construction méthodologique\n\nConclusion : Relier à « donner de l'espace aux idées » — écouter, provoquer avec tact, livrer des résultats prêts à l'action avec mesure d'impact.",
    "tags": [
      "Questions difficiles / pièges"
    ],
    "context": "Clôture — pourquoi vous parmi les candidats",
    "interviewerVariants": [
      "Si on ne retient qu'une raison de vous embaucher ?",
      "Pourquoi vous plutôt qu'un consultant Big Four classique ?"
    ],
    "difficulty": "stress"
  }
];
